name: Build and Deploy to Azure VM (No Docker Hub)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.AZURE_VM_SSH_KEY }}

    - name: Copy project to VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} "rm -rf ~/app && mkdir -p ~/app"
        scp -r ./* ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }}:~/app

    - name: Build and Run Docker on VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.AZURE_VM_USER }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
          cd ~/app
          docker stop app-container || true && docker rm app-container || true
          docker build -t my-app .
          docker run -d --name app-container -p 80:80 my-app
        EOF
